# DATASET_ROOT: It should have two subdirectories called [images] and [masks].
# CHECKPOINT ROOT: A sub-directory will be generated to save logs, plots and checkpoint.
# LOSS_FUNC: Loss-function choices are ["DiceCELoss", "FocalLoss"].
# OPTIMIZER: Choices are ["ADAM", "SGD"].
# LEARNING_RATE: Learning rate value.
# BATCH_SIZE: Batch size value.
# EPOCHS: Number of epochs.
# CROSS_VALIDATION_FOLDS: Number of cross-validation folds (2 or, greater).
# WRITE_CHECKPOINT: If [True], checkpoint will be saved as a .pt file.

DATASET_ROOT: "../datasets/HAM10000/"
CHECKPOINT_ROOT: "../checkpoints/"
LOSS_FUNC:
  - "DiceCELoss"
  - "FocalLoss"
OPTIMIZER: 
  - "ADAM"
  - "SGD"
LEARNING_RATE: 
  - 0.000001
  - 0.00001
  - 0.0001
BATCH_SIZE: 
  - 2
  - 4
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: True