DATASET_ROOT: /content/HAM10000/
CHECKPOINT_ROOT: /content/drive/MyDrive/COLAB/Melanoma_Segmentation/checkpoints/
LOSS_FUNC: DiceCELoss
OPTIMIZER: ADAM
LEARNING_RATE: 0.0001
BATCH_SIZE: 4
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: true
