DATASET_ROOT: ../datasets/HAM10000/
CHECKPOINT_ROOT: ../checkpoints/
LOSS_FUNC: DiceCELoss
OPTIMIZER: SGD
LEARNING_RATE: 0.0001
BATCH_SIZE: 2
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: true
CONFIG_REFERENCE: training_config_11
