DATASET_ROOT: ../datasets/HAM10000/
CHECKPOINT_ROOT: ../checkpoints/
LOSS_FUNC: FocalLoss
OPTIMIZER: SGD
LEARNING_RATE: 1.0e-05
BATCH_SIZE: 2
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: true
CONFIG_REFERENCE: training_config_21
