DATASET_ROOT: /content/HAM10000/
CHECKPOINT_ROOT: /content/checkpoints/
LOSS_FUNC: FocalLoss
OPTIMIZER: SGD
LEARNING_RATE: 0.0001
BATCH_SIZE: 2
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: true
