DATASET_ROOT: /content/HAM10000/
CHECKPOINT_ROOT: /content/checkpoints/
LOSS_FUNC: FocalLoss
OPTIMIZER: SGD
LEARNING_RATE: 1.0e-05
BATCH_SIZE: 4
EPOCHS: 30
CROSS_VALIDATION_FOLDS: 5
WRITE_CHECKPOINT: true
